/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

/**
 *
 * @author Miss KaNiRa
 */
public class MenuFrame extends javax.swing.JFrame {

    /**
     * Creates new form MenuFrame
     */
    public MenuFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_ali = new javax.swing.JButton();
        btn_quiteplace = new javax.swing.JButton();
        btn_jujutsu = new javax.swing.JButton();
        btn_luca = new javax.swing.JButton();
        btn_spiderman = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 700));
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Miss KaNiRa\\Downloads\\spider-man.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(450, 420, 175, 212);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Miss KaNiRa\\Downloads\\ali.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 140, 175, 212);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Miss KaNiRa\\Downloads\\a quite place 2.jpg")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(320, 140, 175, 212);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Miss KaNiRa\\Downloads\\jujutsu kaisen 0.jpg")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(550, 140, 175, 212);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Miss KaNiRa\\Downloads\\luca.jpg")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(200, 420, 175, 212);

        btn_ali.setBackground(new java.awt.Color(255, 204, 204));
        btn_ali.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        btn_ali.setForeground(new java.awt.Color(51, 51, 51));
        btn_ali.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_ali.setLabel("Ali & ratu ratu queens");
        btn_ali.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btn_ali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_aliMouseClicked(evt);
            }
        });
        getContentPane().add(btn_ali);
        btn_ali.setBounds(85, 360, 160, 40);

        btn_quiteplace.setBackground(new java.awt.Color(255, 204, 204));
        btn_quiteplace.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        btn_quiteplace.setForeground(new java.awt.Color(51, 51, 51));
        btn_quiteplace.setText("A Quite Place 2");
        btn_quiteplace.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_quiteplace.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_quiteplace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_quiteplaceMouseClicked(evt);
            }
        });
        getContentPane().add(btn_quiteplace);
        btn_quiteplace.setBounds(330, 360, 160, 40);

        btn_jujutsu.setBackground(new java.awt.Color(255, 204, 204));
        btn_jujutsu.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        btn_jujutsu.setForeground(new java.awt.Color(51, 51, 51));
        btn_jujutsu.setText("Jujutsu Kaisen 0");
        btn_jujutsu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_jujutsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_jujutsuMouseClicked(evt);
            }
        });
        getContentPane().add(btn_jujutsu);
        btn_jujutsu.setBounds(560, 360, 160, 40);

        btn_luca.setBackground(new java.awt.Color(255, 204, 204));
        btn_luca.setFont(new java.awt.Font("Segoe UI Emoji", 0, 20)); // NOI18N
        btn_luca.setForeground(new java.awt.Color(51, 51, 51));
        btn_luca.setText("Luca");
        btn_luca.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_luca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_lucaMouseClicked(evt);
            }
        });
        getContentPane().add(btn_luca);
        btn_luca.setBounds(205, 640, 160, 40);

        btn_spiderman.setBackground(new java.awt.Color(255, 204, 204));
        btn_spiderman.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        btn_spiderman.setForeground(new java.awt.Color(51, 51, 51));
        btn_spiderman.setText("Spider-man : NWH");
        btn_spiderman.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_spiderman.setMargin(new java.awt.Insets(2, 4, 2, 4));
        btn_spiderman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_spidermanMouseClicked(evt);
            }
        });
        getContentPane().add(btn_spiderman);
        btn_spiderman.setBounds(460, 640, 160, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Miss KaNiRa\\Downloads\\800x700 end.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_aliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_aliMouseClicked
        
        TiketOrder to = new TiketOrder("Ali & ratu ratu queens");
        setVisible(false);
        to.setVisible(true);
    }//GEN-LAST:event_btn_aliMouseClicked

    private void btn_quiteplaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_quiteplaceMouseClicked
        
        TiketOrder to = new TiketOrder("A Quite Place 2");
        setVisible(false);
        to.setVisible(true);
    }//GEN-LAST:event_btn_quiteplaceMouseClicked

    private void btn_jujutsuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_jujutsuMouseClicked

        TiketOrder to = new TiketOrder("Jujutsu Kaisen 0");
        setVisible(false);
        to.setVisible(true);
    }//GEN-LAST:event_btn_jujutsuMouseClicked

    private void btn_lucaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lucaMouseClicked

        TiketOrder to = new TiketOrder("Luca");
        setVisible(false);
        to.setVisible(true);
    }//GEN-LAST:event_btn_lucaMouseClicked

    private void btn_spidermanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_spidermanMouseClicked

        TiketOrder to = new TiketOrder("Spider-man : No Way Home");
        setVisible(false);
        to.setVisible(true);
    }//GEN-LAST:event_btn_spidermanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ali;
    private javax.swing.JButton btn_jujutsu;
    private javax.swing.JButton btn_luca;
    private javax.swing.JButton btn_quiteplace;
    private javax.swing.JButton btn_spiderman;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
