/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;


/**
 *
 * @author Miss KaNiRa
 */
public class Output extends javax.swing.JFrame {

    /**
     * Creates new form Output
     */
    public Output() {
        initComponents();
        ta_output.setEditable(false);
        ta_output.setBorder(null);
    }
     
    Human human = new Human();

    public void ta_output(){
       
        ta_output.setText("Detail Transaction"
            + " "
            + human.getTitle()
            + "\n   Name            : " + human.getName()
            + "\n   Phone Number    : " + human.getPhone()
            + "\n   Tickets         : " + human.getAmount()
            + "\n   Day             : " + human.getDay()
            + "\n   Time            : " + human.getTime()
            + "\n   Payment Methods : " + human.getPayment()
            + "\n   Total Payment   : " + human.getTotal()
        );
    }

    // Menampilkan studio sesuai film yg dipilih
    public void setLabelStudio(){

        if (this.human.getTitle("Ali & ratu ratu queens")){
            lbl_studio.setText("1");
        } else if (this.human.getTitle("A Quite Place 2")){
            lbl_studio.setText("2");
        } else if (this.human.getTitle("Jujutsu Kaisen 0")){
            lbl_studio.setText("3");
        } else if (this.human.getTitle("Luca")){
            lbl_studio.setText("4");
        } else {
            lbl_studio.setText("5");
        }
    }


    // Menampilkan seats discroll panel, fungsi "toString' buat ngubah object (check box kursi) jd String (kata/huruf)
    public void setSeats(StringBuilder Seats){
        ta_seats.setText(Seats.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_output = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        ta_seats = new javax.swing.JTextArea();
        btn_exit = new javax.swing.JButton();
        lbl_studio = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 55)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BILL PAYMENT");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 90, 390, 56);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("STUDIO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(579, 230, 130, 32);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SEATS");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(580, 400, 120, 32);

        ta_output.setColumns(20);
        ta_output.setRows(5);
        jScrollPane1.setViewportView(ta_output);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(102, 205, 409, 389);

        ta_seats.setColumns(20);
        ta_seats.setRows(5);
        jScrollPane6.setViewportView(ta_seats);

        getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(580, 450, 123, 126);

        btn_exit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_exit.setText("EXIT");
        btn_exit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_exit);
        btn_exit.setBounds(510, 610, 101, 37);

        lbl_studio.setFont(new java.awt.Font("Segoe UI", 0, 80)); // NOI18N
        lbl_studio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_studio.setToolTipText("");
        getContentPane().add(lbl_studio);
        lbl_studio.setBounds(570, 250, 150, 110);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Miss KaNiRa\\Downloads\\800x700 end (2).png")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, -10, 800, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Output.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Output.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Output.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Output.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Output().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lbl_studio;
    private javax.swing.JTextArea ta_output;
    private javax.swing.JTextArea ta_seats;
    // End of variables declaration//GEN-END:variables
}
